# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/db520f1d-f650-48cd-8202-c8d4fe994f3a";
      fsType = "ext4";
    };
  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7B17-5BB5";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/2051d3c9-bd33-475a-9cf3-d2ec316e5ae9";
      fsType = "btrfs";
      options = [ "x-systemd.automount" "x-systemd.mount-timeout=5s" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/cc1f1660-e31a-4227-8caf-fd648feb8e02";
      fsType = "ext4";
      options = [ "x-systemd.automount" "x-systemd.mount-timeout=5s" ];
    };

  boot.resumeDevice = "/dev/disk/by-uuid/b65da3e6-58f3-494f-b9f9-abc319f66281";

  swapDevices = [ 
   { device = "/dev/disk/by-uuid/cbdd2f3a-2974-47ad-9a93-efa4771f32bd"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.xpadneo.enable = true;
}
